export const api = {
    get_master_data:'/master-data',
    user_notifications: '/notifications',
    user_divisions: '/user-divisions',
    users: '/users',
    user_profile: '/user-profile',
    user_details: '/user-details',
    sequence: '/sequence',
    read_file: '/file/read-file',
    create_file: '/file/create-file',
    get_file: '/file',
    file_details: '/file/details',
    files_for_request: '/file/files-for-request',
    all_files: '/file/files',
    read_request: '/request/read-request',
    create_request: '/request/create-request',
    get_request: '/request',
    request_details: '/request/details',
    requests_for_file: '/request/requests-for-file',
    all_requests: '/request/requests'
}